
image: uprev/mrt 

variables:
  GIT_SUBMODULE_STRATEGY: recursive #pull submodules

stages:          # List of stages for jobs, and their order of execution
  - test
  - commit 


#
# Run unit test and publish results
#
unit-test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags: [mrt]
  script:
    - git submodule foreach git pull origin master #Update the submodule heads to latest commits on master
    - mkdir Test/build  #build unit test
    - cd Test/build
    - cmake ..
    - make
    - ./Test/build/runTests --gtest_output="xml:Test/test-results.xml"  #run unit tests
  artifacts:
    reports:
      junit: Test/test-results.xml

#
# If there are changes (i.e. updates in submodules or docs) push back to the repo
# - This will trigger the docs to rebuild at mrt.readthedocs.io
#

commit:
  tags: [mrt]
  needs: [unit-test]
  stage: commit
  before_script:
    - git config --global user.email "devops@uprev.com"
    - git config --global user.name "gitlab CI"
  script:
    - git submodule foreach git pull origin master  #we have to do this again because we are in a different job. need to find a way to keep workspace..
    - mrt-doc -d doc -c 
    - | 
      CHANGES=$(git status --porcelain | wc -l)
      if [[ "${CHANGES}" -gt 0 ]]; then
        echo "Updating Module heads"
        git add executions.txt
        git commit -m "Module Heads updated in gitlab pipeline"
        git push "https://${GITLAB_USER_NAME}:${CI_ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_REF_NAME}" -o skip-ci
      else
        echo "Nothing to commit"
      fi


#TODO

