name: test
on: push

jobs:
  Module-Unit-Test:
    runs-on: self-hosted
    container:
      image: uprev/mrt
    steps:
         - name: Build and run
           run: |
              git submodule foreach git pull origin master
              mkdir Test/build
              cd Test/build
              cmake ..
              make
              ./Test/build/runTests --gtest_output="xml:Test/test-results.xml" 
         - name: 'Upload Artifact'
           uses: actions/upload-artifact@v3
           with:
            name: test-result
            path: Test/test-results.xml
            retention-days: 5
